v 20130925 2
N 45700 67600 45700 68700 4
N 45700 66700 45700 65000 4
C 47100 68800 1 180 0 resistor-2.sym
{
T 46700 68900 5 10 1 1 0 0 1
refdes=R2
T 46900 68600 5 10 1 1 180 0 1
value=200
}
N 45700 68700 46200 68700 4
N 47100 68700 48200 68700 4
{
T 48400 68700 5 10 1 1 0 0 1
netname=vOut
}
N 47600 65000 45700 65000 4
C 47800 66000 1 90 0 capacitor-1.sym
{
T 47300 66500 5 10 1 1 180 0 1
refdes=C1
T 48200 66500 5 10 1 1 180 0 1
value=10uf
}
N 47600 66000 47600 65000 4
N 47600 66900 47600 68700 4
N 45700 68700 45200 69200 4
{
T 44900 69200 5 10 1 1 0 0 1
netname=vIn
}
C 45500 67600 1 270 0 voltage-3.sym
{
T 46200 67400 5 8 0 0 270 0 1
device=VOLTAGE_SOURCE
T 44700 67300 5 10 1 1 0 0 1
value=AC 1
T 44700 67500 5 10 1 1 0 0 1
refdes=VSIGNAL
}
T 49200 67500 9 10 1 0 0 0 5
One single capacitor in parallel can make a Low Pass Filter.
The plot is a 'frequency sweep' analysis: the simulation
changes the frequency generated by VSIGNAL across a range.
The output plot is output voltage on frequency, in a 
logaritmic scale.
C 46500 64700 1 0 0 gnd-1.sym
{
T 46800 64800 5 10 1 1 0 0 1
netname=0
}
C 49100 66500 1 0 0 spice-directive-1.sym
{
T 49200 66800 5 10 0 1 0 0 1
device=directive
T 49200 66900 5 10 1 1 0 0 1
refdes=A1
T 49100 64800 5 10 1 1 0 0 9
value=.control
* ac analysis
* ac ( DEC | OCT | LIN ) N Fstart Fstop
ac dec 10 1 100k
set color0=rgb:f/f/f
set color1=rgb:0/0/0
set curplottitle="voltages"
plot vout
.endc
}
